### ISSUE TITLE
issue with droplet.take_snapshot()

### ISSUE THREAD

**Issue by ghost** [koalalorenzo/python-digitalocean#116]
```python
droplet.take_snapshot(
    "test-snapshot",
    return_dict=False,
    power_off=True ).wait(update_every_seconds=10)
```

is causing this:

```shell
File "digitalocean/baseapi.py", line 113, in get_data
    raise DataReadError(msg)
digitalocean.baseapi.DataReadError: Droplet is currently on. Please power it off to run this event.
```

This only just started happening a few days ago, and I can't find any changes that may have caused this.

**Comment by koalalorenzo** [comment]
Are you using the last version of python-digitalocean? Why are you calling a method if return_dict is set to True?

**Comment by corndogcomputers** [comment]
I don't have it like that in my script, I was testing and didn't realize I had return_dict set to true for the example I posted.

**Comment by koalalorenzo** [comment]
I am testing this now.

**Comment by giavjeko** [comment]
I'm also getting this error. I'm powering off droplet in separate API call before taking snapshot.
```Python
droplet.power_off(return_dict=False).wait()
```
It seems to go on before power off event is actually finished, so when I try to take snapshot I get the error message reported here.

**Comment by corndogcomputers** [comment]
It's strange. Sometime it works. Like 1 out of every 10 tests.

**Comment by koalalorenzo** [comment]
Are we sure this is not connected with the API behaviour? during this week I don't have time, so if you will open a pull request I will check it later tonight. :( Sorry guys!

**Comment by conorsch** [comment]
@koalalorenzo I can reproduce this as described. Workarounds include powering off the droplet in a separate API call, or allowing the `take_snapshot` method to return a dict.

**Comment by koalalorenzo** [comment]
@conorsch are you using the latest version? I will have a look later today.

**Comment by grajagandev** [comment]
With commit  e2bb8e9 from May 3 I am seeing this as well. I can reliably reproduce it by calling take_snapshot a second time on the same droplet:



`
>>> import os
>>> import digitalocean
>>> manager = digitalocean.Manager(token=os.environ['DOTOKEN'])
>>> stage = manager.get_droplet(16801660)
>>> action = stage.take_snapshot('pool', return_dict = False, power_off = True)
>>> actionphp = stage.take_snapshot('php1', return_dict = False, power_off = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-i686/egg/digitalocean/Droplet.py", line 294, in take_snapshot
  File "build/bdist.linux-i686/egg/digitalocean/Droplet.py", line 171, in _perform_action
  File "build/bdist.linux-i686/egg/digitalocean/Droplet.py", line 116, in get_data
  File "build/bdist.linux-i686/egg/digitalocean/baseapi.py", line 113, in get_data
digitalocean.baseapi.DataReadError: Droplet is currently on. Please power it off to run this event.
`

**Comment by koalalorenzo** [comment]
@grajagandev @conorsch @giavjeko , are you still able to reproduce this error with the latest version?

**Comment by koalalorenzo** [comment]
Closing for inactivity, please re-open if this _bug_ is found again
