### ISSUE TITLE
Intermittent Error related to sshKey already present 

### ISSUE THREAD

**Issue by djsly** [koalalorenzo/python-digitalocean#151]
I often get this exception when creating droplets. Would anyone know what could be causing this ?

Thanks !

```
Traceback (most recent call last):
  File "/root/install_bins/do_rekick.py", line 338, in <module>
    main()
  File "/root/install_bins/do_rekick.py", line 331, in main
    create_env(manager, droplet_list, options.prefix)
  File "/root/install_bins/do_rekick.py", line 245, in create_env
    ssh_keys=[ssh_key])
  File "/root/install_bins/do_rekick.py", line 181, in create_droplet
    droplet.create()
  File "/usr/local/lib/python2.7/dist-packages/digitalocean/Droplet.py", line 498, in create
    "ssh_keys": self.__get_ssh_keys_id_or_fingerprint(),
  File "/usr/local/lib/python2.7/dist-packages/digitalocean/Droplet.py", line 466, in __get_ssh_keys_id_or_fingerprint
    key.create()
  File "/usr/local/lib/python2.7/dist-packages/digitalocean/SSHKey.py", line 68, in create
    data = self.get_data("account/keys/", type=POST, params=input_params)
  File "/usr/local/lib/python2.7/dist-packages/digitalocean/baseapi.py", line 113, in get_data
    raise DataReadError(msg)
digitalocean.baseapi.DataReadError: SSH Key is already in use on your account
```

**Comment by koalalorenzo** [comment]
I think the problem is not with python-digitalocean but with do_rekick.py, since it is trying to create an SSH Key that is already used in your Digital Ocean account (that is an error directly from the digital-ocean API).

**Comment by djsly** [comment]
Thanks, we will look into out do_rekick script !

**Comment by djsly** [comment]
Actually after looking a this in more details, there might be a race condition in the library or a bad regex.

our script simply calls droplet.create twice in a row using the same Key

The first call is supposed to create the key before assigning it to the droplet while the second call should detect that it exists. In some cases it doesn't detect it exists and it tries to recreate it and gets an error that its present. 

```
    # Create SkyDNS droplet
    dns_droplet = create_droplet(prefix + "skydns",
                                 image="17896997",
                                 size="512mb",
                                 ssh_keys=[ssh_key])
    # Create droplets
    for droplet_name in droplet_name_list:
        create_droplet(droplet_name,
                       image="18458248",
                       size="2gb",
                       ssh_keys=[ssh_key])
```

```
def create_droplet(name, image, region="nyc1", size="2gb", ssh_keys=None):
    """Create droplet on DigitalOcean"""
    if ssh_keys is None:
        ssh_keys = []

    droplet = digitalocean.Droplet(token=TOKEN,
                                   name=name,
                                   region=region,
                                   image=image,
                                   size_slug=size,
                                   backups=False,
                                   private_networking=True,
                                   ssh_keys=ssh_keys)
    try:
        droplet.create()
    except Exception as exp:
        print ssh_keys
        raise exp
    return droplet
```

**Comment by koalalorenzo** [comment]
That is weird, because the second time it should be loaded not created, according to this line: https://github.com/koalalorenzo/python-digitalocean/blob/master/digitalocean/Droplet.py#L501

I am guessing then that you are not using an Key object, instead you are using some strings containing the key. My suggestion would be to create a key object for each, and use that in the array.

```python
new_ssh_keys_obj = []
for key_str in ssh_keys
    key = SSHKey()
    key.token = token # don't forget it!
    loaded_key = key.load_by_pub_key(ssh_key)
    if not loaded_key:
        key.public_key = ssh_key #or whatever you have to do
        key.name = "SSH Key %s" % name #Whatever you have
        key.create()
    else:
        key = loaded_key
    
    new_ssh_keys_obj.append(key)

# So you can use it:

dns_droplet = create_droplet(prefix + "skydns",
                                 image="17896997",
                                 size="512mb",
                                 ssh_keys=[ssh_key])
```

**Comment by djsly** [comment]
Correct I was passing ssh_key string!

I have started creating the key manually before hand but was expecting to keep the key string to the create_droplet call. I will convert to an array of Key object instead of Key String !

Thanks for the snippet.

**Comment by koalalorenzo** [comment]
Awesome!
