### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by KahanPrabhu** [koalalorenzo/python-digitalocean#159]
**Error:**
Traceback (most recent call last):
  File "dp.py", line 9, in <module>
    droplet.create()
  File "/usr/local/lib/python2.7/dist-packages/digitalocean/Droplet.py", line 548, in create
    data = self.get_data("droplets", type=POST, params=data)
  File "/usr/local/lib/python2.7/dist-packages/digitalocean/Droplet.py", line 152, in get_data
    data = super(Droplet, self).get_data(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/digitalocean/baseapi.py", line 113, in get_data
    raise DataReadError(msg)
digitalocean.baseapi.DataReadError: Unable to authenticate you.

The Droplet.create() works fine on the Mac, however this is the error I got on an Ubuntu 16.04 64-bit machine.

**Comment by koalalorenzo** [comment]
Are you using the right key/authentication?
It could also be that you don't have the certificates installed, try running:

    sudo apt-get install ca-certificates

**Comment by KahanPrabhu** [comment]
I'm using the right key. That's for sure. 
I tried running the command you suggested but that didn't work either.

**Comment by koalalorenzo** [comment]
I would love to help you, but there must be something wrong you Ubuntu. Are you using python 2 or python 3? If you could share the code it will be easier to help.

**Comment by koalalorenzo** [comment]
Closing for inactivity and lack of information :(
