### ISSUE TITLE
droplet creation issue

### ISSUE THREAD

**Issue by cynicXer** [koalalorenzo/python-digitalocean#228]
When creating a droplet using cloud config data in the "user data" field, the droplet fails to create if an SSH key is included in user section.  The attached error is thrown.  If I copy the cloud config data and manually create an instance in the DO web interface the droplet is created normally.

```
[*] -> Creating droplet...
Traceback (most recent call last):
  File "create_redirector.py", line 194, in <module>
    main()
  File "create_redirector.py", line 176, in main
    args.api_token)
  File "create_redirector.py", line 130, in create_redirectors
    droplet.create()
  File "/media/cynicxer/storage/vmshare/scripts/python/build_digitalocean_redirector/lib/python3.5/site-packages/digitalocean/Droplet.py", line 545, in create
    self.name)
  File "/media/cynicxer/storage/vmshare/scripts/python/build_digitalocean_redirector/lib/python3.5/site-packages/digitalocean/Droplet.py", line 516, in __get_ssh_keys_id_or_fingerprint
    key.create()
  File "/media/cynicxer/storage/vmshare/scripts/python/build_digitalocean_redirector/lib/python3.5/site-packages/digitalocean/SSHKey.py", line 68, in create
    data = self.get_data("account/keys/", type=POST, params=input_params)
  File "/media/cynicxer/storage/vmshare/scripts/python/build_digitalocean_redirector/lib/python3.5/site-packages/digitalocean/baseapi.py", line 172, in get_data
    raise DataReadError(msg)
digitalocean.baseapi.DataReadError: Key invalid, key should be of the format `type key [comment]`
```

**Comment by koalalorenzo** [comment]
Can you share the code that you were running?

**Comment by cynicXer** [comment]
That's the function that runs droplet.create.  It gets a digitalocean.SSHKey object passed to it.
The cloud-config data is in a local text file, it just does a format replace to dump in the public key.

```
config_file = open(cloud_config.txt).read()

while count <= redir_count:
        droplet = digitalocean.Droplet(token=redir_token,
                                       name=base_name + "-" + str(count),
                                       region=random.choice(regions).slug,
                                       image=image,
                                       size_slug=size_slug,
                                       ssh_keys=[key.name],
                                       tags=[redir_tag],
                                       backups=backups,
                                       user_data=config_file.format(
                                           sshkey=key.public_key))                               
        try:
            print("[*] -> Creating droplet...")
            droplet.create()
            print("[*] -> Droplet created. Waiting for droplet availability...")
            actions = droplet.get_actions()
            for action in actions:
                if action.wait(update_every_seconds=5):
                    print("[*] -> Redirector available.")
                    # print("[*] -> Droplet ID: " + str(droplet.id))
                    # print("[*] -> Droplet IP: " + str(droplet.ip_address))
        except digitalocean.DropletError as err:
            print("[*] -> Redirector " + str(droplet.name) +
                  " creation failed: " + str(err))
            break
        else:
            print("[*] -> Redirector created: " + str(droplet.id))
        count += 1
```

**Comment by cynicXer** [comment]
nevermind.  There's something wrong with my cloud config file.  using it through the DO web interface fails silently :P
