### ISSUE TITLE
Python 3 unicode compatibility 

### ISSUE THREAD

**Issue by ThatRubenAguilar** [koalalorenzo/python-digitalocean#237]
When adding tags to droplets via tag object directly I got this error:

```
Traceback (most recent call last):
  File "streambot.py", line 145, in <module>
    get_default_tag_name(), get_default_snapshot_name(), get_default_firewall_name())
  File "streambot.py", line 119, in create_or_get_single_droplet_from_snapshot
    tag.add_droplets([droplet.id])
  File "/home/thatra/Code/streambot/venv/lib/python3.5/site-packages/digitalocean/Tag.py", line 116, in add_droplets
    resources = self.__extract_resources_from_droplets(droplets)
  File "/home/thatra/Code/streambot/venv/lib/python3.5/site-packages/digitalocean/Tag.py", line 93, in __extract_resources_from_droplets
    if isinstance(a_droplet, str) or isinstance(a_droplet, unicode) or isinstance(a_droplet, int):
NameError: name 'unicode' is not defined
```

looking into it I made a patch #236 though it does appear linking tags to droplets via tag object has other issues which will be noted in a different issue.

**Comment by koalalorenzo** [comment]
Merged #237
