### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 820: ordinal not in range(128)

### ISSUE THREAD

**Issue by yurivict** [koalalorenzo/python-digitalocean#265]
```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "setup.py", line 14, in <module>
      long_description = file.read()
    File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 820: ordinal not in range(128)
  ```

Version 1.14.0

**Comment by wacuuu** [comment]
Is this even reproducible? Or this is caused by special characters from droplet/object description.

**Comment by koalalorenzo** [comment]
Closing for inactivity! Feel free to comment or open a new one if needed!
