### ISSUE TITLE
can't able to add droplet  under the LoadBalancer?

### ISSUE THREAD

**Issue by GOPIPACHA** [koalalorenzo/python-digitalocean#314]
Hi i am trying to add droplet to my load balancer but I am  not able to do,is  there  any specfic way to add droplets under the load balancer if so can you guide me please?

"""
import digitalocean
manager = digitalocean.Manager(token="tokenn-api")
load_balancer = manager.get_all_load_balancers()
droplets = manager.get_all_droplets()
lb=digitalocean.LoadBalancer(token="token-api")
check= load_balancer[0]
test=droplets[1]
check.add_droplets(test)
print('added')
""

when i runn the above code I am getting below  traceback
Traceback (most recent call last):
  File "/home/mypathshala-1/PycharmProjects/digital_ocen/LB.py", line 7, in <module>
    check.add_droplets(190354296)
  File "/home/mypathshala-1/PycharmProjects/digital_ocen/venv/lib/python3.7/site-packages/digitalocean/LoadBalancer.py", line 291, in add_droplets
    params={"droplet_ids": droplet_ids}
  File "/home/mypathshala-1/PycharmProjects/digital_ocen/venv/lib/python3.7/site-packages/digitalocean/baseapi.py", line 198, in get_data
    raise NotFoundError()
digitalocean.NotFoundError

can anyone help me out out  of  this thanks in advance

**Comment by GOPIPACHA** [comment]
I think i will not get any responce from here?

**Comment by andrewsomething** [comment]
This looks to be a bug. I've proposed a fix in: https://github.com/koalalorenzo/python-digitalocean/pull/316

**Comment by GOPIPACHA** [comment]
Hi,
Thanks for your responce!

is this probllem is resolved?
